name: Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Dev Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 107.23.136.20
          username: ubuntu
          key: ${{ secrets.HOSTINGERSSHKEY }}
          command_timeout: 30m
          script: |
            bash /home/ubuntu/frontend/deploy-docker.sh dev

      - name: Slack Success (Dev)
        if: success()
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          payload=$(jq -n \
            --arg text "✅ DEV Deployment Successful 🚀 | Repo: ${{ github.repository }} | Commit: ${COMMIT_MESSAGE}" \
            '{text: $text}')
          curl --fail-with-body -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
            -H "Content-type: application/json" \
            -d "$payload"

      - name: Slack Failure (Dev)
        if: failure()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H "Content-type: application/json" \
          -d "{\"text\":\"❌ DEV Deployment Failed 🚨 | Repo: ${{ github.repository }}\"}"


  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 98.93.251.56
          username: ubuntu
          key: ${{ secrets.PRODKEY }}
          command_timeout: 30m
          script: |
            bash /home/ubuntu/frontend/deploy-docker.sh main

      - name: Slack Success (Prod)
        if: success()
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          payload=$(jq -n \
            --arg text "🚀 PROD Deployment Successful ✅ | Repo: ${{ github.repository }} | Commit: ${COMMIT_MESSAGE}" \
            '{text: $text}')
          curl --fail-with-body -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
            -H "Content-type: application/json" \
            -d "$payload"

      - name: Slack Failure (Prod)
        if: failure()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H "Content-type: application/json" \
          -d "{\"text\":\"🔥 PROD Deployment FAILED ❌ | Repo: ${{ github.repository }}\"}"
